name: Build

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and publish to GitHub Pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
